apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weather-service
spec:
  selector:
    app: weather-service
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP