apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rajeev3012/weather-service.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: weather
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true